const { Client } = require('pg');
require('dotenv').config();
const { getConnectionOptions } = require('../src/config/db_postgres');

const statements = [
  `CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS categorias_nombre_lower_unique ON categorias (LOWER(nombre))`,
  `CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    contacto VARCHAR(100),
    telefono VARCHAR(20),
    email VARCHAR(100),
    direccion VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS proveedores_nombre_idx ON proveedores (LOWER(nombre))`,
  `CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    dni VARCHAR(20),
    telefono VARCHAR(20),
    email VARCHAR(100),
    direccion VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS clientes_dni_unique ON clientes (dni) WHERE dni IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS clientes_nombre_idx ON clientes (LOWER(nombre))`,
  `CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    rol TEXT NOT NULL DEFAULT 'vendedor' CHECK (rol IN ('admin', 'gerente', 'supervisor', 'vendedor', 'cajero', 'almacen')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS usuarios_username_lower_unique ON usuarios (LOWER(username))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_lower_unique ON usuarios (LOWER(email)) WHERE email IS NOT NULL`,
  `ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0`,
  `CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    codigo VARCHAR(50),
    precio_compra NUMERIC(12,2) CHECK (precio_compra IS NULL OR precio_compra >= 0),
    precio_venta NUMERIC(12,2) NOT NULL CHECK (precio_venta >= 0),
    stock_actual INTEGER NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    stock_minimo INTEGER NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    id_categoria INTEGER REFERENCES categorias(id_categoria) ON DELETE SET NULL,
    id_proveedor INTEGER REFERENCES proveedores(id_proveedor) ON DELETE SET NULL,
    imagen VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS productos_codigo_lower_unique ON productos (LOWER(codigo)) WHERE codigo IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS productos_categoria_idx ON productos (id_categoria)`,
  `CREATE INDEX IF NOT EXISTS productos_proveedor_idx ON productos (id_proveedor)`,
  `CREATE TABLE IF NOT EXISTS caja (
    id_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    fecha_apertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP,
    monto_apertura NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (monto_apertura >= 0),
    monto_cierre NUMERIC(12,2) CHECK (monto_cierre IS NULL OR monto_cierre >= 0),
    monto_esperado NUMERIC(12,2),
    diferencia NUMERIC(12,2),
    estado TEXT NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada')),
    observaciones TEXT,
    semantica_legacy BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS caja_usuario_abierta_unique ON caja (id_usuario) WHERE estado = 'abierta'`,
  `CREATE INDEX IF NOT EXISTS caja_fecha_apertura_idx ON caja (fecha_apertura)`,
  `CREATE TABLE IF NOT EXISTS ventas (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER REFERENCES clientes(id_cliente) ON DELETE SET NULL,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    id_caja INTEGER REFERENCES caja(id_caja) ON DELETE SET NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal NUMERIC(12,2) CHECK (subtotal IS NULL OR subtotal >= 0),
    iva NUMERIC(12,2) CHECK (iva IS NULL OR iva >= 0),
    descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    total NUMERIC(12,2) CHECK (total IS NULL OR total >= 0),
    saldo_pendiente NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (saldo_pendiente >= 0),
    metodo_pago VARCHAR(50) NOT NULL,
    estado TEXT NOT NULL DEFAULT 'completada' CHECK (estado IN ('pendiente', 'completada', 'anulada')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS ventas_fecha_idx ON ventas (fecha)`,
  `CREATE INDEX IF NOT EXISTS ventas_cliente_idx ON ventas (id_cliente)`,
  `CREATE INDEX IF NOT EXISTS ventas_caja_idx ON ventas (id_caja)`,
  `CREATE INDEX IF NOT EXISTS ventas_saldo_idx ON ventas (saldo_pendiente) WHERE saldo_pendiente > 0`,
  `CREATE TABLE IF NOT EXISTS venta_detalle (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER REFERENCES ventas(id_venta) ON DELETE RESTRICT,
    id_producto INTEGER REFERENCES productos(id_producto),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) CHECK (precio_unitario IS NULL OR precio_unitario >= 0),
    subtotal NUMERIC(12,2) CHECK (subtotal IS NULL OR subtotal >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS venta_detalle_venta_idx ON venta_detalle (id_venta)`,
  `CREATE INDEX IF NOT EXISTS venta_detalle_producto_idx ON venta_detalle (id_producto)`,
  `CREATE TABLE IF NOT EXISTS compras (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    estado TEXT NOT NULL DEFAULT 'completada' CHECK (estado IN ('completada', 'anulada')),
    observaciones TEXT,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS compra_detalles (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra INTEGER NOT NULL REFERENCES compras(id_compra) ON DELETE CASCADE,
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_costo NUMERIC(12,2) NOT NULL CHECK (precio_costo >= 0),
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0)
  )`,
  `CREATE INDEX IF NOT EXISTS compra_detalles_compra_idx ON compra_detalles (id_compra)`,
  `ALTER TABLE compra_detalles ADD COLUMN IF NOT EXISTS precio_compra_anterior NUMERIC(12,2)`,
  `CREATE TABLE IF NOT EXISTS cotizaciones (
    id_cotizacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER REFERENCES clientes(id_cliente) ON DELETE SET NULL,
    fecha_emision TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_validez DATE,
    subtotal NUMERIC(12,2) CHECK (subtotal IS NULL OR subtotal >= 0),
    iva NUMERIC(12,2) CHECK (iva IS NULL OR iva >= 0),
    descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    total NUMERIC(12,2) CHECK (total IS NULL OR total >= 0),
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobada', 'rechazada', 'convertida')),
    observaciones TEXT,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS cotizacion_detalles (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cotizacion INTEGER NOT NULL REFERENCES cotizaciones(id_cotizacion) ON DELETE CASCADE,
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) CHECK (precio_unitario IS NULL OR precio_unitario >= 0),
    descuento_producto NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento_producto >= 0),
    subtotal NUMERIC(12,2) CHECK (subtotal IS NULL OR subtotal >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS cotizacion_detalles_cotizacion_idx ON cotizacion_detalles (id_cotizacion)`,
  `CREATE TABLE IF NOT EXISTS devoluciones (
    id_devolucion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL REFERENCES ventas(id_venta) ON DELETE RESTRICT,
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    motivo VARCHAR(255),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_reembolso NUMERIC(12,2) NOT NULL CHECK (monto_reembolso >= 0),
    metodo_reembolso VARCHAR(50) NOT NULL,
    estado TEXT NOT NULL DEFAULT 'completada' CHECK (estado IN ('completada', 'anulada')),
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS devoluciones_venta_producto_idx ON devoluciones (id_venta, id_producto)`,
  `CREATE TABLE IF NOT EXISTS ajustes_inventario (
    id_ajuste INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
    stock_anterior INTEGER NOT NULL CHECK (stock_anterior >= 0),
    stock_nuevo INTEGER NOT NULL CHECK (stock_nuevo >= 0),
    motivo VARCHAR(255) NOT NULL,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS log_acciones (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER,
    username VARCHAR(50),
    accion VARCHAR(50) NOT NULL,
    entidad VARCHAR(50) NOT NULL,
    entidad_id INTEGER,
    detalles VARCHAR(500),
    ip VARCHAR(45),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS pagos_venta (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL REFERENCES ventas(id_venta) ON DELETE RESTRICT,
    id_caja INTEGER REFERENCES caja(id_caja) ON DELETE SET NULL,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('abono', 'reembolso')),
    monto NUMERIC(12,2) NOT NULL CHECK (monto > 0),
    metodo VARCHAR(50) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS pagos_venta_venta_idx ON pagos_venta (id_venta)`,
  `CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      NEW.updated_at = CURRENT_TIMESTAMP;
      RETURN NEW;
    END;
    $$`,
  `DROP TRIGGER IF EXISTS categorias_updated_at ON categorias`,
  `CREATE TRIGGER categorias_updated_at BEFORE UPDATE ON categorias FOR EACH ROW EXECUTE FUNCTION set_updated_at()`,
  `DROP TRIGGER IF EXISTS clientes_updated_at ON clientes`,
  `CREATE TRIGGER clientes_updated_at BEFORE UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION set_updated_at()`,
  `DROP TRIGGER IF EXISTS proveedores_updated_at ON proveedores`,
  `CREATE TRIGGER proveedores_updated_at BEFORE UPDATE ON proveedores FOR EACH ROW EXECUTE FUNCTION set_updated_at()`,
  `DROP TRIGGER IF EXISTS productos_updated_at ON productos`,
  `CREATE TRIGGER productos_updated_at BEFORE UPDATE ON productos FOR EACH ROW EXECUTE FUNCTION set_updated_at()`,
  `DROP TRIGGER IF EXISTS usuarios_updated_at ON usuarios`,
  `CREATE TRIGGER usuarios_updated_at BEFORE UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION set_updated_at()`
];

const versionTwoStatements = [
  `ALTER TABLE venta_detalle DROP CONSTRAINT IF EXISTS venta_detalle_id_venta_fkey`,
  `ALTER TABLE venta_detalle ADD CONSTRAINT venta_detalle_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES ventas(id_venta) ON DELETE RESTRICT`,
  `ALTER TABLE devoluciones DROP CONSTRAINT IF EXISTS devoluciones_id_venta_fkey`,
  `ALTER TABLE devoluciones ADD CONSTRAINT devoluciones_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES ventas(id_venta) ON DELETE RESTRICT`,
  `ALTER TABLE pagos_venta DROP CONSTRAINT IF EXISTS pagos_venta_id_venta_fkey`,
  `ALTER TABLE pagos_venta ADD CONSTRAINT pagos_venta_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES ventas(id_venta) ON DELETE RESTRICT`
];

const versionThreeStatements = [
  `UPDATE caja SET fecha_apertura = COALESCE(fecha_apertura, created_at, CURRENT_TIMESTAMP) WHERE fecha_apertura IS NULL`,
  `ALTER TABLE caja ALTER COLUMN fecha_apertura SET DEFAULT CURRENT_TIMESTAMP`,
  `ALTER TABLE caja ALTER COLUMN fecha_apertura SET NOT NULL`,
  `ALTER TABLE pagos_venta ADD COLUMN IF NOT EXISTS id_devolucion INTEGER REFERENCES devoluciones(id_devolucion) ON DELETE RESTRICT`,
  `CREATE UNIQUE INDEX IF NOT EXISTS pagos_venta_devolucion_unique ON pagos_venta (id_devolucion) WHERE id_devolucion IS NOT NULL AND tipo = 'reembolso'`
];

const versionFourStatements = [
  `ALTER TABLE caja ADD COLUMN IF NOT EXISTS semantica_legacy BOOLEAN NOT NULL DEFAULT FALSE`,
  `UPDATE caja c SET semantica_legacy = TRUE
   WHERE c.estado = 'cerrada'
     AND c.monto_esperado IS NOT NULL
     AND ABS(c.monto_esperado - (
       c.monto_apertura
       + COALESCE((SELECT SUM(v.total) FROM ventas v WHERE v.id_caja = c.id_caja AND v.estado = 'completada'), 0)
       + COALESCE((SELECT SUM(p.monto) FROM pagos_venta p WHERE p.id_caja = c.id_caja AND p.tipo = 'abono'), 0)
       - COALESCE((SELECT SUM(d.monto_reembolso) FROM devoluciones d JOIN ventas v ON v.id_venta = d.id_venta WHERE v.id_caja = c.id_caja AND d.estado = 'completada'), 0)
     )) < 0.01
     AND ABS(c.monto_esperado - (
       c.monto_apertura
       + COALESCE((SELECT SUM(v.total) FROM ventas v WHERE v.id_caja = c.id_caja AND v.estado = 'completada' AND v.metodo_pago = 'efectivo'), 0)
       + COALESCE((SELECT SUM(p.monto) FROM pagos_venta p WHERE p.id_caja = c.id_caja AND p.tipo = 'abono' AND p.metodo = 'efectivo'), 0)
       - COALESCE((SELECT SUM(d.monto_reembolso) FROM devoluciones d JOIN ventas v ON v.id_venta = d.id_venta WHERE v.id_caja = c.id_caja AND d.estado = 'completada' AND d.metodo_reembolso = 'efectivo'), 0)
     )) >= 0.01`,
  `ALTER TABLE ventas DROP CONSTRAINT IF EXISTS ventas_saldo_total_check`,
  `ALTER TABLE ventas ADD CONSTRAINT ventas_saldo_total_check CHECK (saldo_pendiente >= 0 AND (total IS NULL OR saldo_pendiente <= total))`,
  `ALTER TABLE pagos_venta DROP CONSTRAINT IF EXISTS pagos_venta_id_devolucion_tipo_check`,
  `ALTER TABLE pagos_venta ADD CONSTRAINT pagos_venta_id_devolucion_tipo_check CHECK (id_devolucion IS NULL OR tipo = 'reembolso')`
];

async function migrate() {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL no configurada');
  }

  const client = new Client(getConnectionOptions(process.env.DATABASE_URL));

  await client.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT pg_advisory_xact_lock(724319)');
    for (const statement of statements) {
      await client.query(statement);
    }
    await client.query('INSERT INTO schema_migrations (version) VALUES (1) ON CONFLICT (version) DO NOTHING');
    const versionResult = await client.query('SELECT COALESCE(MAX(version), 0)::integer AS version FROM schema_migrations');
    if (versionResult.rows[0].version < 2) {
      for (const statement of versionTwoStatements) {
        await client.query(statement);
      }
      await client.query('INSERT INTO schema_migrations (version) VALUES (2) ON CONFLICT (version) DO NOTHING');
    }
    const versionAfterTwo = await client.query('SELECT COALESCE(MAX(version), 0)::integer AS version FROM schema_migrations');
    if (versionAfterTwo.rows[0].version < 3) {
      for (const statement of versionThreeStatements) {
        await client.query(statement);
      }
      await client.query('INSERT INTO schema_migrations (version) VALUES (3) ON CONFLICT (version) DO NOTHING');
    }
    const versionAfterThree = await client.query('SELECT COALESCE(MAX(version), 0)::integer AS version FROM schema_migrations');
    if (versionAfterThree.rows[0].version < 4) {
      for (const statement of versionFourStatements) {
        await client.query(statement);
      }
      await client.query('INSERT INTO schema_migrations (version) VALUES (4) ON CONFLICT (version) DO NOTHING');
    }
    await client.query('COMMIT');
    console.log('Esquema PostgreSQL aplicado correctamente');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    await client.end();
  }
}

if (require.main === module) {
  migrate().catch((error) => {
    console.error('Error de migración PostgreSQL:', error.code || error.message);
    process.exit(1);
  });
}

module.exports = { migrate, statements, versionTwoStatements, versionThreeStatements, versionFourStatements };
